### PR TITLE
Upgraded packages to latest compatible versions

### PR DESCRIPTION
**Pull request by mehra-sourav**
Date: 05-03-2024

Developer Name:  Sourav Mehra

---

## Issue Ticket Number
[#1938](https://github.com/Real-Dev-Squad/website-backend/issues/1938)

## Description

This PR updates all dependencies in package.json to the latest compatible versions.

### Documentation Updated?

- [ ] Yes
- [x] No

### Under Feature Flag

- [ ] Yes
- [x] No

### Database Changes

- [ ] Yes
- [x] No

### Breaking Changes

- [ ] Yes
- [x] No

### Development Tested?

- [x] Yes
- [ ] No

## Screenshots
<details>

</details>

image

## Test Coverage
<details>

Unit Test Coverage
image

Integration Test Coverage
image

</details>

## Additional Notes

The failing test cases are also failing locally and have nothing to do with my changes.

image

image

### CODE REVIEW

**Review by Achintya-Chatterjee — CHANGES_REQUESTED** [review]
@mehra-sourav take a pull from develop and update the test coverage

**Comment by mehra-sourav** [comment]
> @mehra-sourav take a pull from develop and update the test coverage

Prakash has already updated this branch with the latest from develop. The failing tests are working now.

**Comment by mehra-sourav** [comment]
> @mehra-sourav take a pull from develop and update the test coverage

Prakash has already updated this branch with the latest from develop. The failing tests are working now.

**Review by prakashchoudhary07 — APPROVED** [review]

**Comment by ankushdharkar** [comment]
I am running into issues after removing `node_modules` and installing everything again:

```
22 warnings and 4 errors generated.
make: *** [Release/obj.target/re2/lib/addon.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (<path>/1943-packages-upgrade/node_modules/node-gyp/lib/build.js:201:23)
gyp ERR! stack     at ChildProcess.emit (node:events:518:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
gyp ERR! System Darwin 23.4.0
gyp ERR! command \"~/.volta/tools/image/node/20.11.1/bin/node\" \"<path>/1943-packages-upgrade/node_modules/re2/node_modules/.bin/node-gyp\" \"rebuild\"
gyp ERR! cwd <path>/1943-packages-upgrade/node_modules/re2
```

**Pull request merged**
