### PR TITLE
feature-members api initial depreciation

### PR DESCRIPTION
**Pull request by aakankshadhurandhar**
- Removed all the code for member API 

Closes: #608

### CODE REVIEW

**Comment by poonammohata** [comment]
@aakankshadhurandhar members.js file in validators folder is still there, that is also not getting used anywhere other than members API

**Review by Muralidhar22 — COMMENTED** [review]
@aakankshadhurandhar 
I have created an issue to make the change before members api deprecate
[https://github.com/Real-Dev-Squad/website-dashboard/issues/237](https://github.com/Real-Dev-Squad/todo-action-items/issues/110)

**Comment by vinit717** [comment]
closing this as it is done 
https://github.com/Real-Dev-Squad/website-members/issues/547

**Comment by vinit717** [comment]
closing this as the task is done
https://github.com/Real-Dev-Squad/website-members/issues/547

**Pull request closed without merging**
