### PR TITLE
add art endpoints

### LINKED ISSUE #533: API Endpoints for Art Feature
We need to make three endpoints i.e. GET, GET all and POST for CSS Art Feature.
 
 Get - /arts/:artId
 Get all - /arts
 Post - /arts/add
 
Parameters which are required :
 - Username - (string)
 - Title - (string)
 - CSS - (string)
 - Price - (number)
 - Created At - (string)
 - Unique ID - (string)

### PR DESCRIPTION
**Pull request by anmoldewanrai**
Closes #533 

Following routes added:

- arts/
- arts/user/self
- arts/user/add
- arts/user/:userid

### CODE REVIEW

**Review by MehulKChaudhari — DISMISSED** [review]
LGTM.

**Review by pallabez — APPROVED** [review]
LGTM

**Comment by pallabez** [comment]
Integration test for `/arts/user/:userId` by @RahulGoyal-tech in 
- #562

**Comment by rohan09-raj** [comment]
> Integration test for `/arts/user/:userId` by @RahulGoyal-tech in
> 
> * [Integration Test for api improvement #562](https://github.com/Real-Dev-Squad/website-backend/pull/562)

Thanks @pallabez, for creating the issue and making Rahul write tests for it

**Review by harshith-venkatesh — APPROVED** [review]

**Pull request merged**
