### PR TITLE
Removed `Controller` from filename under folder `controller` and updated references to the files

### LINKED ISSUE #280: Remove suffix `controller` from controller files
The `...Controller` in each filename inside a `controllers` folder is unnecessary redundant context. Let's remove it please

image

### PR DESCRIPTION
**Pull request by K-ash-ish**
Removed Controller inside Filename in controller folder
It was my first time Please tell me Why it is showing checks failed

Closes #280

### CODE REVIEW

**Comment by ankushdharkar** [comment]
Hi @K-ash-ish, thank you for making those changes.

Can we add a meaningful title to this PR please? "Required changes done" doesn't give us a good idea of what changes are you referring to>

Also, try to have helpful messages in your commits too. That helps to track down changes in future. Seeing 10 "changes done" doesn't tell you what the changes were.

**Review by ankushdharkar — CHANGES_REQUESTED** [review]
@K-ash-ish It seems most of our tests are failing, indicating that the changes to the code may have some unintentional bugs, which we should investigate

image

When you changed the filenames, did you update the references to those files elsewhere in the code?

**Comment by K-ash-ish** [comment]
> Hi @K-ash-ish, thank you for making those changes.
> 
> Can we add a meaningful title to this PR please? "Required changes done" doesn't give us a good idea of what changes are you referring to>
> 
> Also, try to have helpful messages in your commits too. That helps to track down changes in future. Seeing 10 "changes done" doesn't tell you what the changes were.

Sorry for that I'm a beginner just starting my journey in contributing to OS I'll keep these things in mind from next time. Thank  You for your advice

**Comment by K-ash-ish** [comment]
> @K-ash-ish It seems most of our tests are failing, indicating that the changes to the code may have some unintentional bugs, which we should investigate
> 
> image
> 
> When you changed the filenames, did you update the references to those files elsewhere in the code?

Ohh , I only changed the filenames under controller folder. I forgot that these files will be in use somewhere. I'll try to change them too.

**Comment by swarajpure** [comment]
@K-ash-ish Thank you for this PR!
We (Real Dev Squad) are a community of developers consisting on college students and working professionals. We communicate over Discord. You might want to join the community, you'll get A LOT to learn 😄
We have got projects like this repository which use simple HTML, CSS and vanilla JavaScript and also projects based on React, Ember and Vue for frontend and on Node for backend. Since we're open source, you can show your work which you do here to the interviewers as well 🎉 
No matter what your expertise level is, we've always got something for everyone! ⚡ 

Invitation link: https://discord.gg/akgChXXF

**Review by swarajpure — APPROVED** [review]
Looks good to me. Thanks for this one!

Congratulations on your first pull request in Real Dev Squad 🥳

**Comment by K-ash-ish** [comment]
> @K-ash-ish Thank you for this PR!
> We (Real Dev Squad) are a community of developers consisting on college students and working professionals. We communicate over Discord. You might want to join the community, you'll get A LOT to learn 😄
> We have got projects like this repository. There are projects which use simple HTML, CSS and vanilla JavaScript and also projects based on React, Ember and Vue for frontend and on Node for backend (this project). Since we're open source, you can show your work which you do here to the interviewers as well 🎉
> No matter what your expertise level is, we've always got something for everyone! ⚡
> 
> Invitation link: https://discord.gg/exqmZqn4

i'm currently a beginner learning languages trying to contribute to open source projects But will definitely join the channel as i'll be learning these things in future and it will be very helpful for me to be around you peoples  :smiley:

**Comment by K-ash-ish** [comment]
> Looks good to me. Thanks for this one!
> 
> Congratulations on your first pull request in Real Dev Squad 🥳
**THANK YOU** this was my first ever commit :smiley: :smiley:

**Pull request merged**
