### PR TITLE
Dev to Main Sync

### LINKED ISSUE #2129: Lazy load Groups Page data
### Issue Description
The /groups page currently loads all groups at once, leading to potential performance issues as the number of groups increases in the future. This can cause the page to lag, affecting the overall user experience.

### Expected Behavior
The /groups page should implement lazy loading, where only a subset of groups is loaded initially.
Additional groups should load dynamically as the user scrolls or interacts with the page, ensuring smooth performance.
The page should remain responsive and efficient, regardless of the total number of groups.

### Current Behavior
All groups are loaded simultaneously, which may cause the page to lag, especially as more groups are added in the future.
This can lead to a poor user experience, with slower load times and decreased responsiveness.

### Screenshots
NA

### Reproducibility

 - [x] This issue is reproducible
 - [ ] This issue is not reproducible

### Steps to Reproduce
1.Visit the /groups page.
2.Observe the loading behavior and any lag when all groups are displayed at once.
3.Consider scenarios where the number of groups is significantly higher than the current count.

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [x] Medium
 - [ ] Low

### Additional Information
Implementing lazy loading will improve the page's efficiency and ensure it can handle future scalability.
This enhancement will provide a better user experience by maintaining responsiveness as the number of groups increases.

### Checklist

- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.

### LINKED ISSUE #2219: Deprecate /self API Endpoints and Provide Meaningful Alternative Routes
### Issue Description

Deprecate the /self API endpoint across all routes from the website-backend. And provide a alternative route that will serve the purpose of /self.

Below is the mentioned list of routes where /self is currently being used:

1. - [x] GET     /arts/user/self  
2. - [x] GET    /extensionRequests/self  
3. - [x] GET    /stocks/user/self  
4. - [x] GET    /tasks/self  
5. - [x] PATCH  /tasks/self/:id  
6. - [x] PATCH  /tasks/assign/self  
7. - [x] POST   /trading/stock/new/self  
8. - [x] PATCH  /users/self  
9. - [x] PUT    /users/self/intro  
10. - [x] GET    /userStatus/self  
11. - [x] PATCH  /userStatus/self  

### Expected Behavior

The API Endpoint should have a more meaningful name.

### Reproducibility

 - [x] This issue is reproducible
 - [ ] This issue is not reproducible

### Severity/Priority
 - [ ] Critical
 - [x] High
 - [ ] Medium
 - [ ] Low

### Checklist

- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.

### LINKED ISSUE #2223: Fix data obfuscation and ID field issues in updateUser function
### Issue Description
The `updateUser` function in `controllers/users.js` has two critical issues:
1. It merges obfuscated email and phone number data into the user record.
2. It incorrectly includes an `id` field when updating user data, potentially causing conflicts with the document's actual ID.

### Expected Behavior
1. The function should merge unobfuscated email and phone number data into the user record.
2. The `id` field should be excluded when updating user data.

### Current Behavior
1. Obfuscated email and phone number data from `fetchProfileDiff` are being merged into the user record.
2. An `id` field is included in the data used to update the user record, which may interfere with the document's actual ID.

### Screenshots
N/A

### Reproducibility

 - [x] This issue is reproducible
 - [ ] This issue is not reproducible

### Steps to Reproduce
1. Call the `updateUser` function with a valid `profileDiffId`.
2. Check the updated user record in the database.
3. Observe that the email and phone number are obfuscated and an extra `id` field is present.

### Severity/Priority
 - [ ] Critical
 - [x] High
 - [ ] Medium
 - [ ] Low

### Additional Information
The `fetchProfileDiff` function returns obfuscated data for UI purposes, but this data is being directly used to update the user record. We need to implement a way to get both obfuscated (for UI) and unobfuscated (for database updates) data.

### Proposed Solution
1. Create a new function in `profileDiffsQuery` that returns unobfuscated data for database updates.
2. Modify the `updateUser` function to use this new function for getting unobfuscated data.
3. Implement a filtering step to remove the `id` field before updating the user record.

### Checklist

- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.

### PR DESCRIPTION
**Pull request by Achintya-Chatterjee**
Date: `December 22, 2024`

Developer Name: @Achintya-Chatterjee @vikasosmium @RahulGoyal-tech 

---

## Issue Ticket Number

- Closes #2129
- Closes #2219 
- Closes #2223 
## PRs going in this sync

- #2291 
- #2313 
- #2316  
- #2317 
- #2320  
- #2310 
- #2256 
### Documentation Updated?

- [x] Yes
- [ ] No

### Under Feature Flag

- [ ] Yes
- [x] No

### Database Changes

- [ ] Yes
- [x] No

### Breaking Changes

- [ ] Yes
- [x] No

### Development Tested?

- [x] Yes
- [ ] No

## Screenshots
<details>
<summary>Screenshot 1</summary>

-` without dev flag /discord-actions/groups `

https://github.com/user-attachments/assets/0c1de7a0-cb6c-4dc8-b528-edeaf2b4bc33
- with dev=true flag /discord-actions/groups?dev=true

https://github.com/user-attachments/assets/3e76a207-4526-4831-bd68-4c0ea9472328

</details>

## Test Coverage
<details>
<summary>Screenshot 1</summary>

Screenshot 2024-12-28 at 01 37 24
Screenshot 2024-12-28 at 01 37 38

</details>

### CODE REVIEW

**Comment by vikasosmium** [comment]
### Staging Evidence
## Pic 1
image
## Pic 2
image
## Pic 3
image
## Pic 4
image
## Pic 5
image

**Comment by vikasosmium** [comment]
### Staging Evidence - #2316 

Screenshot 2024-12-28 014241

Screenshot 2024-12-28 014321

Screenshot 2024-12-28 014338

Screenshot 2024-12-28 014634

Screenshot 2024-12-28 014858

Screenshot 2024-12-28 014942

Screenshot 2024-12-28 015001

image

**Comment by vikasosmium** [comment]
### Staging Evidence - #2317 

Screenshot 2024-12-28 020258

image

image

**Comment by vikasosmium** [comment]
### Staging - #2320 

image

image

image

**Review by iamitprakash — APPROVED** [review]

**Comment by listiclehub1** [comment]
Developer Name: Utkarsh Bansal

## Issue Ticket Number
- Closes #2216 
## PRs going in this sync
- #2278 
## Staging Testing 

https://github.com/user-attachments/assets/618f1b4b-da67-4459-b941-a484a609db04

**Pull request merged**
