### PR TITLE
dev to main sync

### PR DESCRIPTION
**Pull request by shubhamsigdar1**
Developer Name: @Ajeyakrishna-k 

PR Number(s): 
- #1609 
- #1610 
- #1611 
- #1616
- #1617 
- #1622 

Issue Ticket Number: 
- #1582 
- #1583 

Backend changes
-   [x]  Yes
-   [ ]  No

Frontend Changes
-   [x]  Yes
-   [ ]  No

Is Under Feature Flag

-   [x]  Yes
-   [ ]  No

Database changes

-   [x]  Yes
-   [ ]  No

Breaking changes (If your feature is breaking/missing something please mention pending tickets)

-   [ ]  Yes
-   [x]  No

Deployment notes
Any special instructions for the deployment
- [x] No

Tested in staging

-   [x]  Yes
-   [ ]  No

https://github.com/Real-Dev-Squad/website-backend/assets/98796547/92574ce3-3605-43d1-9063-68c53c55e441

https://github.com/Real-Dev-Squad/website-backend/assets/98796547/550894b1-d62d-4b9e-8025-e1da1f574f27

### CODE REVIEW

**Comment by suryxks** [comment]
Developer Name: @suryxks 

PR Number(s): [#1603](https://github.com/Real-Dev-Squad/website-backend/pull/1603)
Issue Ticket Number: [#1449 ](https://github.com/Real-Dev-Squad/website-backend/issues/1449)

Backend changes

-   [x]  Yes
-   [ ]  No

Frontend Changes

-   [ ]  Yes
-   [x]  No

Is Under Feature Flag

-   [x]  Yes
-   [ ]  No

Database changes

-   [ ]  Yes
-   [x]  No

Breaking changes (If your feature is breaking/missing something please mention pending tickets)

-   [ ]  Yes
-   [x]  No

Deployment notes
Any special instructions for the deployment
- [x] No
Tested in staging

-   [x]  Yes
-   [ ]  No
stage-1
staging-2
staging-3
staging-4

List of PRs going in this sync
#1609 
#1603 
#1592

**Comment by ardourApeX** [comment]
### Developer Name: Joy Gupta

### PR Number(s): 1618

### Issue Ticket Number:
- https://github.com/Real-Dev-Squad/website-backend/issues/1515

### Backend Changes
- [x] Yes
- [ ] No
 
### Frontend Changes
- [ ] Yes
- [x] No

### Is Under Feature Flag
- [x] Yes
- [ ] No

### Database changes: 
- [x] Yes
- [ ] No

### Breaking changes (If your feature is breaking/missing something please mention pending tickets): 
- [ ] Yes
- [x] No

### Deployment notes: 
Please make sure that the following composite index is already created: 
> - [Issue for creating composite index on Prod](https://github.com/Real-Dev-Squad/website-backend/issues/1621)
> - image



### Tested in staging
- [x] Yes
- [ ] No

### List of PRs going in this Sync
NA

### Proposal Doc
- https://docs.google.com/document/d/1sf-BAs7C6wmfjRVS-82X492hcb_7jAfIM-7pWtizuXE/edit

### QA Instructions, Screenshots, Recordings

**1. Fetching logs with dev flag enabled**
Expected Result: Name field should be present in the logs
image

**2. Fetching logs without the dev field being enabled**
Expected Result: The name field should not be present in the logs
image

**3. Fetching self-extension request in dev mode**
Expected Result: reviewedBy field should be present 
image


**4. Fetching self-extension request without dev mode**
Expected Result: reviewedBy field should not be present 
image

**5. Changes made by super user in extension request**
While approving/denying, userId should be present in meta
image
Edit logs should be generated and userId should be present in meta
image

**Review by Ajeyakrishna-k — CHANGES_REQUESTED** [review]
Will approve after verifying my changes.

**Review by Ajeyakrishna-k — APPROVED** [review]
Verified my changes

**Review by ardourApeX — APPROVED** [review]

**Pull request merged**
