### PR TITLE
Dev to main sync

### PR DESCRIPTION
**Pull request by prakashchoudhary07**
Date: 09-1-24

Developer Name: @prakashchoudhary07 

----

PR's going in 
- #1839 
- #1742 
- #1852

(Developer)s Name
- @prakashchoudhary07 
- @satyam73 
- @sahsisunny 

Is Under Feature Flag 
- [ ] Yes
- [x] No

Database changes
- [ ] Yes
- [x] No

Breaking changes (If your feature is breaking/missing something please mention pending tickets)
- [ ] Yes
- [x] No

Is Development Tested?

- [x] Yes
- [ ] No

Is it tested in staging?

- [x] Yes
- [ ] No

### Add relevant Screenshot below ( e.g test coverage etc. )

https://github.com/Real-Dev-Squad/website-backend/pull/1841#issuecomment-1881758886

### CODE REVIEW

**Comment by satyam73** [comment]
Staging proof of #1839

image
> get request to get invite for user

image
> post request if user invite is already present

image
> post request for invitation code

**Comment by satyam73** [comment]
## Staging working proof of #1742
image
> Get request with status query param initial connection with `data: null`

image
> Get request with questionId and status query param initial connection with `data: null`

image
> Post API `/answers`

image
> Get api triiger when post api triggers

image
> Unauthorized if user is not super user or member

image
> Succesful patch request when `member` is `true`

image
> Succesful patch request when `super_user` is `true`

image
> status query with APPROVED value (get request) triggers when there is any update happens with PATCH request `/answers`

**Comment by Ajeyakrishna-k** [comment]
Looks good 👍

**Review by satyam73 — APPROVED** [review]

**Comment by sahsisunny** [comment]
# 1852
image

**Review by sahsisunny — APPROVED** [review]

**Pull request merged**
