### PR TITLE
Dev to Main Sync

### LINKED ISSUE #2245: Store "Unverified" Role in Database on User Join and Remove upon Verification
### Issue Description

When a new user joins Discord, they are assigned an "Unverified" role/tag. However, this role is currently not stored in the database for tracking. The goal is to update the system so that this "Unverified" role is stored in the database as well. When a user completes the /verify command and authorizes themselves, the "Unverified" role should be removed from both the Discord and the database.

### Expected Behavior

1. When a new user joins Discord:

    - "Unverified" role is assigned to the user in Discord.
    - "Unverified" role is recorded in the database against the user.

3. When a user executes /verify and successfully authorizes:

    - "Unverified" role is removed from both the Discord tag and the database record.

### Current Behavior

- The "Unverified" role is applied to the user in Discord but is not saved in the database.
- Upon verification, there is no removal of the "Unverified" role from the database, as it is not stored there currently.

### Reproducibility

 - [ ] This issue is reproducible
 - [X] This issue is not reproducible

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [X] Medium
 - [ ] Low

### Checklist

- [X] I have read and followed the project's code of conduct.
- [X] I have searched for similar issues before creating this one.
- [X] I have provided all the necessary information to understand and reproduce the issue.
- [X] I am willing to contribute to the resolution of this issue.

### LINKED ISSUE #2246: Standardize User Identification Field in Logs Collection for Consistent Querying
### Issue Description
Currently, the logs collection includes two different fields, createdBy and userId, for user identification within the meta field. This inconsistency complicates queries for logs associated with specific users, as it requires checking both fields. We need to standardize the field name to userId across all log entries.

### Expected Behavior
All entries in the logs collection should use a consistent field, userId, for user identification within the meta field. This will allow for uniform querying of logs by userId without having to handle cases where createdBy is used instead.

### Current Behavior
Some documents in the logs collection use meta.createdBy while others use meta.userId. This inconsistency makes it more complex to fetch logs for a user, as queries need to account for both fields.

### Reproducibility

 - [ ] This issue is reproducible
 - [x] This issue is not reproducible

### Severity/Priority
 - [ ] Critical
 - [x] High
 - [ ] Medium
 - [ ] Low

### Checklist

- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.

### LINKED ISSUE #2275: Add filtering query to search the logs
### Issue Description
we need to search the logs based on username and timestamp

### Reproducibility

 - [ ] This issue is reproducible
 - [ ] This issue is not reproducible

### Steps to Reproduce
1. 
2. 

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [ ] Medium
 - [ ] Low

### Checklist

- [ ] I have read and followed the project's code of conduct.
- [ ] I have searched for similar issues before creating this one.
- [ ] I have provided all the necessary information to understand and reproduce the issue.
- [ ] I am willing to contribute to the resolution of this issue.

### LINKED ISSUE #2280: Remove dev feature flag  from DELETE "/groups/:groupId" API
### Issue Description

Remove the dev feature flag  from DELETE "/groups/:groupId" API as the issue has been tested on production, hence requires dev flag removal

### Expected Behavior

The feature should be accessible to the super users without using the "?dev=true" query.

### Current Behavior

The feature is currently accessible only to super users using the "?dev=true" query.

### Reproducibility

 - [x] This issue is reproducible
 - [ ] This issue is not reproducible

### Steps to Reproduce
 Hit the endpoint "https://staging-api.realdevsquad.com/discord-actions/groups/{groupId}" on Postman without using the dev flag and see the error.

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [ ] Medium
 - [x] Low

### Checklist

- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.

### LINKED ISSUE #2288: Remove dev feature flag from arts/userId?dev=true API Endpoint
### Issue Description

Remove dev feature flag from arts/userId?dev=true API Endpoint
### Reproducibility

 - [x] This issue is reproducible
 - [ ] This issue is not reproducible

### Steps to Reproduce
1. 
2. 

### Severity/Priority
 - [ ] Critical
 - [x] High
 - [ ] Medium
 - [ ] Low

### Checklist

- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.

### PR DESCRIPTION
**Pull request by Achintya-Chatterjee**
Date: 04 Dec 2024

Developer Name: @VaibhavSingh8 @vikhyat187 @vinit717 @shobhan-sundar-goutam @vikasosmium 

---

## Issue Ticket Number

- Closes #2280 
- Closes #2246
- Closes #2245 
- Closes #2288 
- Closes #2275 
## PR's to Sync
- https://github.com/Real-Dev-Squad/website-backend/pull/2271
- #2281 
- #2226 
- #2248
- #2257 
- #2289 
- #2269
### Documentation Updated?

- [ ] Yes
- [x] No

### Under Feature Flag

- [ ] Yes
- [x] No

### Database Changes

- [ ] Yes
- [x] No

### Breaking Changes

- [ ] Yes
- [x] No

### Development Tested?

- [x] Yes
- [ ] No

## Screenshots

<details>
<summary>Screenshot 1</summary>

</details>

### CODE REVIEW

**Comment by vinit717** [comment]
### Proof for #2226 and #2248

image
image

**Comment by VaibhavSingh8** [comment]
### Proof for #2280 


https://github.com/user-attachments/assets/72ba9174-c80c-473d-8604-d58e09203493

**Comment by shobhan-sundar-goutam** [comment]
**Proof for #2257** 

https://github.com/user-attachments/assets/f858503b-594b-4e49-bf66-17a0023a6428

**Comment by VinuB-Dev** [comment]
Proof for https://github.com/Real-Dev-Squad/website-backend/pull/2267 and https://github.com/Real-Dev-Squad/website-backend/pull/2268

https://github.com/Real-Dev-Squad/website-backend/pull/2267:

Screenshot 2024-12-06 at 8 33 21 AM
Screenshot 2024-12-06 at 8 36 54 AM

https://github.com/Real-Dev-Squad/website-backend/pull/2268:

Screenshot 2024-12-06 at 8 35 07 AM
Screenshot 2024-12-06 at 8 36 15 AM

**Comment by vikasosmium** [comment]
Staging Evidence #2289 

image

**Review by prakashchoudhary07 — APPROVED** [review]

**Pull request merged**
