### PR TITLE
Added last used in field in post group API

### PR DESCRIPTION
**Pull request by skv93-coder**
Date: 19-12-23

Developer Name: @skv93-coder 

----

## Issue Ticket Number:- 
- #1707 

## Description: 
Added lastUsedOn field.

Is Under Feature Flag 
- [ ] Yes
- [x] No

Database changes
- [ ] Yes
- [x] No

Breaking changes (If your feature is breaking/missing something please mention pending tickets)
- [ ] Yes
- [x] No

Is Development Tested?

- [x] Yes
- [ ] No

Tested in staging?

- [ ] Yes
- [x] No

### Add relevant Screenshot below ( e.g test coverage etc. )

image
image

### CODE REVIEW

**Review by iamitprakash — APPROVED** [review]

**Review by ajoykumardas12 — APPROVED** [review]

**Comment by ajoykumardas12** [comment]
Some group data won't have `lastUsedOn` field until used once after this change, right?
If yes, this can have problems when trying to access this property during sorting groups.

**Comment by skv93-coder** [comment]
> Some group data won't have `lastUsedOn` field until used once after this change, right? If yes, this can have problems when trying to access this property during sorting groups.

Yes, you are right that will be handled in the frontend side

**Comment by ajoykumardas12** [comment]
> Yes, you are right that will be handled in the frontend side

You could also run migration script to add this field to existing group data. For example #1715

**Comment by skv93-coder** [comment]
> > Yes, you are right that will be handled in the frontend side
> 
> You could also run migration script to add this field to existing group data. For example #1715

Yes but null check will be needed even then. So adding migration will not solve it. Eg. Newly created groups will not have last joined date. So, migration will not solve null issue.

**Pull request merged**
