### PR TITLE
Dev to Main Sync

### PR DESCRIPTION
**Pull request by heyrandhir**
**Developer Name:**   @heyrandhir @skv93-coder @j24m 

### Action required before deployment : 
Need to create index with following link

https://console.firebase.google.com/v1/r/project/read-dev-shu/firestore/indexes?create_composite=Ck9wcm9qZWN0cy9yZWFkLWRldi1zaHUvZGF0YWJhc2VzLyhkZWZhdWx0KS9jb2xsZWN0aW9uR3JvdXBzL3Byb2dyZXNzZXMvaW5kZXhlcy9fEAEaCgoGdGFza0lkEAEaCAoEdHlwZRABGggKBGRhdGUQARoMCghfX25hbWVfXxAB

https://console.firebase.google.com/v1/r/project/read-dev-shu/firestore/indexes?create_composite=Ck9wcm9qZWN0cy9yZWFkLWRldi1zaHUvZGF0YWJhc2VzLyhkZWZhdWx0KS9jb2xsZWN0aW9uR3JvdXBzL3Byb2dyZXNzZXMvaW5kZXhlcy9fEAEaCgoGdGFza0lkEAEaCAoEdHlwZRABGggKBGRhdGUQAhoMCghfX25hbWVfXxAC

**PR Number(s) :** 
- [] #1587 
- [] #1590
- [] #1595

**Backend changes :**

- [x] Yes
- [ ] No

**Frontend Changes :**

- [ ] Yes
- [x] No        

**Database changes :**

- [x] Yes (index creation for #1590)
- [] No

**Breaking changes (If your feature is breaking/missing something please mention pending tickets) :**

- [x] No
- [ ] Yes:- 

**Deployment notes(Any special instructions for the deployment) :**

- [x] No

**Tested in staging**

- [x] Yes
- [ ] No

### CODE REVIEW

**Comment by heyrandhir** [comment]
Staging Proof for https://github.com/Real-Dev-Squad/website-backend/pull/1587

image

**Comment by skv93-coder** [comment]
### Staging proof https://github.com/Real-Dev-Squad/website-backend/pull/1590

image

image

image

**Comment by ankushdharkar** [comment]
@heyrandhir The first index was already existing in prod. The second one has been created. This PR is now unblocked. ✅

**Comment by heyrandhir** [comment]
> @heyrandhir The first index was already existing in prod. The second one has been created. This PR is now unblocked. ✅

CC @skv93-coder

**Comment by j24m** [comment]
### Working Proof for PR : 
- https://github.com/Real-Dev-Squad/website-backend/pull/1595

image

**Pull request merged**
