### PR TITLE
Using firebase tools from local node_modules

### LINKED ISSUE #358: Use firebase-tools from local node_modules
Let's use the firestore tools from the local project, instead of having to install the package globally

### PR DESCRIPTION
**Pull request by ankushdharkar**
Closes #358, #361

~~Waiting on resolving the failing test for /tasks~~

### CODE REVIEW

**Review by swarajpure — COMMENTED** [review]
Wouldn't we need to need to make change in the shell scripts? 
Wouldn't shell script fail to recognise what's `firebase emulators` without it being installed globally? 🤔 
https://github.com/Real-Dev-Squad/website-backend/blob/09c53d861f1133e9ab2bea3a1421bcec855f8716/scripts/tests/testIntegration.sh#L7

What I'm saying is, will we need give path to `firebase-emulators` in this case?


Or are the tests working fine with these changes?

**Review by ankurnarkhede — CHANGES_REQUESTED** [review]
@ankushdharkar , as we are adding firebase-tools in package.json, should we remove the github actions command to install it globally at: https://github.com/Real-Dev-Squad/website-backend/blob/develop/.github/workflows/test.yml#L30 ?

**Comment by ankushdharkar** [comment]
@ankurnarkhede https://github.com/Real-Dev-Squad/website-backend/issues/361 :D

**Comment by ankurnarkhede** [comment]
Also, how is this dependent on the /tasks tests as per you mentioned in the PR description?

**Comment by swarajpure** [comment]
Your local setup would still have firebase-tools globally installed, which makes the tests run on local

Also on CI, this PR might be passing because we're installing firebase-tools globally in CI as well.

I guess the change mentioned by @ankurnarkhede should be a part of this PR itself. What do you think? @ankurnarkhede @ankushdharkar

**Comment by ankushdharkar** [comment]
@ankurnarkhede It's not. My /tasks were failing until yesterday. Not sure why they are passing today 🤔

**Comment by ankushdharkar** [comment]
I like that idea @swarajpure. Made the required change. Thanks!

**Review by swarajpure — APPROVED** [review]
Looks good to me! 👌🏻

**Review by ankurnarkhede — COMMENTED** [review]
LGTM ✅

**Review by ankurnarkhede — APPROVED** [review]

**Review by ankurnarkhede — APPROVED** [review]

**Pull request merged**
